name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake -B ${{ github.workspace }}/build -DBUILD_TESTS=ON -DTEST_GROUPS="ray_info"
    - name: Build
      run: cmake --build ${{ github.workspace }}/build
    - name: Install
      run: cmake --install ${{ github.workspace }}/build --config Debug
    - name: Test
      run: cd ${{ github.workspace }}/bin/test && ctest -C Debug
